# Generated by Django 3.2.7 on 2021-09-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fechaCreado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified',
        ),
    ]
