# Generated by Django 3.2.7 on 2021-09-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permits', '0002_auto_20210904_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('towns', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='apellido',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='lastName',
        ),
    ]
