# Generated by Django 3.2.7 on 2021-09-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permits', '0003_auto_20210905_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='towns',
            field=models.JSONField(blank=True),
        ),
    ]
