# Generated by Django 3.2.7 on 2021-09-05 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permits', '0004_alter_departments_towns'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
    ]
