# Generated by Django 3.2.9 on 2021-12-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_pet_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='isAdopted',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='isSterilized',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='receiver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_set', to='backend_app.user'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sender_set', to='backend_app.user'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='state',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('ACE', 'Aceptada'), ('DEN', 'Denegada')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='pet',
            name='isLike',
            field=models.ManyToManyField(to='backend_app.User'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_set', to='backend_app.user'),
        ),
    ]
