# Generated by Django 3.2.9 on 2021-12-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_auto_20211202_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='isAdopted',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=5),
        ),
        migrations.AddField(
            model_name='pet',
            name='isSterilized',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=5),
        ),
    ]
